name = "my-personal-screenshot-via-email"
main = "src/index.ts"
compatibility_date = "2024-01-01"
# Optional: account_id = "..." # This can be automatically fetched or set as an environment variable
[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[vars]
BREVO_API_KEY="you brevo api it's safer to upload via cloudflare console after building"
BREVO_FROM_EMAIL="Exapmle@Example.com"
SCREENSHOT_API_URL="https://api.screen-shot.xyz"
